In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


### Introduction to Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
print(scalar.ndim)
print(scalar.item())

0
7


In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
print("Number of closing sqauare brackets",vector.ndim)
print("Shape of vector", vector.shape)

Number of closing sqauare brackets 1
Shape of vector torch.Size([2])


In [ ]:
#Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,3,8]],
                        [[3,4,5],
                         [5,3,2],
                          [3,1,2]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 3, 8]],

        [[3, 4, 5],
         [5, 3, 2],
         [3, 1, 2]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 3, 3])

In [ ]:
tensor[1]

tensor([[3, 4, 5],
        [5, 3, 2],
        [3, 1, 2]])

### Random Tensors

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.7653, 0.1672, 0.0261, 0.6228],
         [0.5617, 0.2075, 0.4555, 0.3239],
         [0.8856, 0.3417, 0.4756, 0.5154]],

        [[0.1105, 0.7646, 0.6966, 0.4651],
         [0.9352, 0.6518, 0.8347, 0.6653],
         [0.4174, 0.1388, 0.5441, 0.1368]]])

In [ ]:
#Create a random tensor similar shape to an image
rand_image_Size_tensor = torch.rand(3,224,224)
rand_image_Size_tensor.shape, rand_image_Size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

In [ ]:
# Zeros and Ones
zeros = torch.zeros(size=(3,4), dtype = int)
zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [ ]:
ones = torch.ones(size=(3,4))
ones.dtype # default is float32

torch.float32

In [ ]:
ten_range = torch.arange(start = 1, end= 100, step = 5)
ten_range

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
# Create tensor like ...
ten_zeros = torch.zeros_like(input = ten_range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
float_32_tensor = torch.rand(size = (3,4),
                             dtype = None,
                             device = None,
                             requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
print(float_32_tensor)
print(float_16_tensor)

tensor([[0.6515, 0.6499, 0.9498, 0.3378],
        [0.1665, 0.7067, 0.9951, 0.4157],
        [0.0012, 0.8266, 0.6378, 0.6772]])
tensor([[0.6514, 0.6499, 0.9497, 0.3376],
        [0.1665, 0.7065, 0.9951, 0.4158],
        [0.0012, 0.8267, 0.6377, 0.6772]], dtype=torch.float16)


In [ ]:
float_32_tensor*float_16_tensor

tensor([[4.2438e-01, 4.2236e-01, 9.0202e-01, 1.1404e-01],
        [2.7722e-02, 4.9931e-01, 9.9026e-01, 1.7283e-01],
        [1.5300e-06, 6.8328e-01, 4.0671e-01, 4.5861e-01]])

## Manipulating Tensors - Tensor Operations

In [ ]:
# Create a tensor and add a 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.add(tensor,10), torch.mul(tensor,10)

(tensor([11, 12, 13]), tensor([10, 20, 30]))

### Matrix Multiplication

- Element-wise multiplication
- Matrix multiplication

In [ ]:
tensor*tensor # element wise multiplication

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor,tensor) #

tensor(14)

In [ ]:
tensor_2d = torch.rand(3,4)
torch.matmul(tensor_2d.T, tensor_2d) #inner dimensions should match

tensor([[1.0599, 0.9874, 0.6252, 0.7297],
        [0.9874, 1.0741, 0.5922, 0.8552],
        [0.6252, 0.5922, 0.8363, 0.9183],
        [0.7297, 0.8552, 0.9183, 1.1886]])

Tensor Aggregation

In [ ]:
x = torch.arange(0,100,10)
x.dtype

torch.int64

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32)) #mean wont work with int64 dtype

tensor(45.)

In [ ]:
 torch.sum(x)

tensor(450)

In [ ]:
# Find the position of min and max
torch.argmin(x)

tensor(0)

In [ ]:
torch.argmax(x)

tensor(9)

### Reshaping, Stacking, Squeezing and Unsqueezing
- **Reshape** - reshapes an input tensor to a defined shape
- **View** - return the view of a input tensor of certain shape but keep the same memory as the original tensor
- **Stacking** - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
- **Squeeze** - removes all 1 dimensions from a tensor
- **Unsqueeze** - add a 1 dimension to a target tensor
- **Permute** - Return a view of the input with dims swapped in a certain way

In [ ]:
x_reshaped = x.reshape(2,5)
print("original shape", x.shape)
print("reshaped",x_reshaped.shape)

original shape torch.Size([10])
reshaped torch.Size([2, 5])


In [ ]:
print("original tensor: ", x)
print("reshaped tensor: ",x_reshaped)

original tensor:  tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
reshaped tensor:  tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])


In [ ]:
z = x.view(5,2)
z, z.shape

(tensor([[ 0, 10],
         [20, 30],
         [40, 50],
         [60, 70],
         [80, 90]]),
 torch.Size([5, 2]))

In [ ]:
 # changing z changes x as well, as they both share the same memory
 z[:,0] = 5
 z, x

(tensor([[ 5, 10],
         [ 5, 30],
         [ 5, 50],
         [ 5, 70],
         [ 5, 90]]),
 tensor([ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]))

In [ ]:
# Stack tensors on each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90],
        [ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90],
        [ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90],
        [ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]])

In [ ]:
# Stack tensors  side by side
x_hstack = torch.stack([x,x,x,x], dim = 1)
x_hstack

tensor([[ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [ 5,  5,  5,  5],
        [30, 30, 30, 30],
        [ 5,  5,  5,  5],
        [50, 50, 50, 50],
        [ 5,  5,  5,  5],
        [70, 70, 70, 70],
        [ 5,  5,  5,  5],
        [90, 90, 90, 90]])

In [ ]:
#squeeze
x_reshaped = x.reshape(1,10)
x_squeezed = torch.squeeze(x_reshaped)

print("tensor before squeeze: ", x_reshaped)
print("shape before squeeze: ", x_reshaped.shape)
print("tensor after squeeze: ",x_squeezed)
print("shape after squeeze: ",x_squeezed.shape) # removes all 1 dimensions


tensor before squeeze:  tensor([[ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]])
shape before squeeze:  torch.Size([1, 10])
tensor after squeeze:  tensor([ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90])
shape after squeeze:  torch.Size([10])


In [ ]:
# Unsqueeze
print("previous target: ", x_squeezed)
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print("new target: ", x_unsqueezed)
print("shape : ", x_unsqueezed.shape)

previous target:  tensor([ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90])
new target:  tensor([[ 5, 10,  5, 30,  5, 50,  5, 70,  5, 90]])
shape :  torch.Size([1, 10])


In [ ]:
# Permute
x_original = torch.rand(3, 224, 224) #channels, height and width

# Rearrange the dimension order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0, width, channels, height
x_permuted.shape

#Permute is a view, view shares the same memory as the original tensor

torch.Size([224, 3, 224])

### Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Index on 0th dimension
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Index on 1st dimension
x[0][1]

tensor([4, 5, 6])

In [ ]:
# Index on 2nd dimension
x[0][1][2]

tensor(6)

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

### Pytorch tensors and Numpy

In [ ]:
import numpy as np

array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_array = tensor.numpy()
numpy_array

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

### Reproducibility (trying to take random out of random)

- To reduce the randomness in neural nets, Pytorch comes up with a concept called **randomseed**

In [ ]:
A = torch.rand(3,4)
B = torch.rand(3,4)

A == B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3,4)


torch.manual_seed(RANDOM_SEED)
D = torch.rand(3,4)

print(C)
print(D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


Running tensors and pytorch objects on gpus

In [ ]:
!nvidia-smi

Tue Oct 14 14:11:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   66C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Check for GPU Access with Pytorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### Putting tensors (or models) on GPU

In [ ]:
tensor = torch.tensor([1,2,3], device = 'cpu')
tensor.device

device(type='cpu')

In [ ]:
# Move tensor to gpu
tensor_to_gpu = tensor.to(device)
tensor_to_gpu.device

device(type='cuda', index=0)

#### Move tensors back to cpu

In [ ]:
# tensor_to_gpu.numpy()
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# /tmp/ipython-input-1168329131.py in <cell line: 0>()
#       1 # Move tensors back to cpu
# ----> 2 tensor_to_gpu.numpy()

# TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_on_cpu = tensor_to_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

Exercises : https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

github : https://github.com/mrdbourke/pytorch-deep-learning